server:
  port: 6060
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  configuration:
    aggressive-lazy-loading: true
  mapper-locations: classpath:mapper/**/*.xml
