server:
  port: 8006
spring:
  application:
    name: cloud-consul-payment8006
  cloud:
    consul:
      host: 192.168.152.134
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        hostname: 192.168.152.134
