spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/security
    username: root

mybatis-plus:
  configuration:
    aggressive-lazy-loading: true

server:
  port: 6060