server:
  port: 8802
spring:
  application:
    name: cloud-stream-comsumer
  rabbitmq:
    host: centos.com
    password: dhf200827
    username: danghf
    port: 5672
  cloud:
    stream:
      binders: # rabbitmq配置
        rabbitmq-0:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: centos.com
                password: dhf200827
                username: danghf
                port: 5672
      bindings: # 绑定信息 集合中的key由 通道名-out/in-数字组成
        input-in-0: # 通道名称，input，消费者
          destination: topicExchange # 交换机名称
          content-type: application/json
          binder: rabbitmq-0 # 绑定的rabbit名称
          group: groupA
eureka:
  instance:
    instance-id: consumer8802
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka