server:
  port: 7001

Eureka:
  instance: # 实例
    hostname: eureka7001.com
#    hostname: localhost # eureka服务端实例名称
  client:
    # false 表示 不注册 服务中心自己
    register-with-eureka: false
    # false 标识自己端是服务中心，维护服务实例，不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与 Eureka Service 交互的地址查询服务和注册服务都依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    # 关闭自我保护，服务不可用，立即剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000