spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true #开起RestFul风格
    contentnegotiation:
      favor-parameter: true #开启参数内容协商
      parameter-name: format
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - classpath:/templates/
      cache:
        max-age: 3600 #缓存时间


  thymeleaf:
    suffix: .html #Controller跳转到html页面配置
    prefix: classpath:/templates/ #Controller跳转到html页面配置
  servlet:
    multipart:
      max-file-size: 10MB #文件上传大小限制
      max-request-size: 100MB #总请求大小限制
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/boot

    druid:
      aop-patterns: com.localhost.dhf.bootjdbc.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true #default false
        # 监控页账号密码：
        login-username: root
        login-password: root
        resetEnable: false #是否有重置按钮default false
        allow:  #白名单
        deny:  #黑名单

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'  #排除


      filter: #对filters详细设置
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true #慢查询
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            drop-table-allow: false #不允许删表

  jdbc:
    template:
      query-timeout: 10 #查询超时时间 默认单位为 s
      fetch-size: 100 #每次查询的数据量 默认单位为条

server:
  port: 8080 #端口
  error:
    path: /error

# 配置mybatis规则
#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置
#  configuration: #config配置后，就不需要config-location
#    map-underscore-to-camel-case: true #开启驼峰命名
# 配置mybatis-plus规则
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名