server:
  port: 9002
spring:
  application:
    name: nacos-producer
  cloud:
    nacos:
      discovery:
        server-addr: centos.com:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"