server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka  # 集群
    fetch-registry: true
    register-with-eureka: true


