server:
  port: 9003
spring:
  application:
    name:  alibaba-server
  cloud:
    nacos:
      discovery:
        server-addr: centos.com:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"