server:
  port: 8080
spring:
  application:
    name: cloud-openfeign-order8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#ribbon:
#  # 建立连接所用时间
#  ConnectTimeout: 5000
#  # 建立连接后，服务器读取到可用资源使用时间
#  ReadTimeout: 5000

feign:
  client:
    config:
      default:
        read-timeout: 6000 # 毫秒
        connect-timeout: 6000
logging:
  level:
    # feign日志以那个级别监测哪个接口
    com.dhf.feignClient.PaymentService: debug