server:
  port: 800
spring:
  application:
    name: cloud-consul-order80
  cloud:
    consul:
      host: 192.168.152.134
      port: 8500
      discovery:
        service-name: ${spring.application.name}